### ISSUE TITLE
Display of all browser windows

### ISSUE THREAD

**Issue by Migotes** [okaryo/TabTabTab#192]
## Describe the bug
If you have many browser windows open, TabTabTab cannot display them all.

## To Reproduce
1. Set the TabTabTab width to 400.
2. Open a lot of windows
3. Open TabTabTab and see that you can't see all windows in the window selection at the top.

## Expected behavior
I would expect a scroll bar so that all windows can be displayed in TabTabTab.

## Screenshots
![Screenshot 2023-10-01 161137](https://github.com/okaryo/TabTabTab/assets/38452654/7290a3ae-4caf-409f-9580-7a1e7142b5b4)

## System information
- OS: Windows 11
- Browser: Microsoft Edge or Google Chrome
- Version of TabTabTab: 2.19.1

**Comment by okaryo** [comment]
done by #202
