### ISSUE TITLE
Enable sorting of tabs

### ISSUE THREAD

**Issue by okaryo** [okaryo/TabTabTab#304]
## Idea
* Add sorting as one of the actions for windows.
* Allow sorting by domain or subdomain in ascending order.

**Comment by okaryo** [comment]
idea
* sort by title or domain, subdomain
* enable setting default sort rule
* add sort action to window actions menus

**Comment by garypeebles** [comment]
Yes, please add asap: sorting options> A-Z ascending & descending order, and Most Recent. Then we'll be cooking good!
