### ISSUE TITLE
Several options to open a new tab

### ISSUE THREAD

**Issue by Storkur** [okaryo/TabTabTab#353]
## Description
Open new tab in :
1. current group (new tab button on group title)
2. next to current tab  (new tab button on tab title)
3. common new tab (chrome default, new tab button on extensions main panel)

## Use case
1. A user has a tab group "Tabs_group1" active. The user opens a new tab and it is created immediately inside this group. 
2. A user has a tab group "Tabs_group1" and a tab "Tab1" active.
The user wants to immediately open a tab next to "Tab1"

## Additional context
Similar behavior is implemented in the extension  https://chromewebstore.google.com/detail/tab-manager-in-side-panel/dhdfjphlghgaokjflinlfcacdafpmiom
When you hover over the title of a tab or group, a "+" button appears on the right side

## P.S.
Thanks for your extension!! 👍

**Comment by okaryo** [comment]
@Storkur 
Thank you for submitting the issue!

Indeed, the features you've mentioned sound like valuable additions to the extension. I often find myself right-clicking browser tabs to open new ones or duplicating them, and having the ability to do this directly within TabTabTab would certainly enhance its convenience.

I'll be addressing this in the near future, so please stay tuned.

If you have a moment, I'd greatly appreciate it if you could leave a review on the store. Your support means a lot!
